spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/laundry
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    url: jdbc:mariadb://localhost:3306/laundry
    username: root
    password: vbn752014&
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  messages:
    basename: messages
    encoding: UTF-8

  mvc:
    hidden-method:
      filter:
        enabled: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG